/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package regisztracio;

/**
 *
 * @author SimonGergő(SZOFT_202
 */
public class RegisztraciosPanel extends javax.swing.JFrame {

    /**
     * Creates new form RegisztraciosPanel
     */
    public RegisztraciosPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngIgenNem = new javax.swing.ButtonGroup();
        btnReg = new javax.swing.JButton();
        chbElfogad = new javax.swing.JCheckBox();
        jpSzemelyes = new javax.swing.JPanel();
        jtfTelefon = new javax.swing.JTextField();
        jlNev = new javax.swing.JLabel();
        jtfEmail = new javax.swing.JTextField();
        jlTelefon = new javax.swing.JLabel();
        jlEmail = new javax.swing.JLabel();
        jtfNev = new javax.swing.JTextField();
        jtfTelefon2 = new javax.swing.JTextField();
        jlTelefon2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jpSzemelyes1 = new javax.swing.JPanel();
        jcbHadsereg = new javax.swing.JComboBox<>();
        jlFegyver = new javax.swing.JLabel();
        jrbIgen = new javax.swing.JRadioButton();
        jrbNem = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jpFeltoltes = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnFeltoltes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Südwind");

        btnReg.setText("Regisztráció");

        chbElfogad.setText("Elfogadom a regisztrációs feltételeket");

        jpSzemelyes.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Személyes"));

        jlNev.setText("Név:");

        jlTelefon.setText("Tel.:");

        jlEmail.setText("E-mail:");

        jlTelefon2.setText("Egyesület:");

        javax.swing.GroupLayout jpSzemelyesLayout = new javax.swing.GroupLayout(jpSzemelyes);
        jpSzemelyes.setLayout(jpSzemelyesLayout);
        jpSzemelyesLayout.setHorizontalGroup(
            jpSzemelyesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSzemelyesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpSzemelyesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlNev)
                    .addComponent(jlEmail)
                    .addComponent(jlTelefon)
                    .addComponent(jlTelefon2))
                .addGap(18, 18, 18)
                .addGroup(jpSzemelyesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfEmail)
                    .addComponent(jtfNev)
                    .addComponent(jtfTelefon, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(jtfTelefon2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpSzemelyesLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jlEmail, jlNev, jlTelefon});

        jpSzemelyesLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtfEmail, jtfNev, jtfTelefon});

        jpSzemelyesLayout.setVerticalGroup(
            jpSzemelyesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSzemelyesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpSzemelyesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNev))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpSzemelyesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpSzemelyesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlTelefon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpSzemelyesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfTelefon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlTelefon2))
                .addContainerGap())
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/sudwind.png"))); // NOI18N
        jLabel1.setToolTipText("");

        jpSzemelyes1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jcbHadsereg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Kérem Válasszon-", "RKKA", "WH", "MKH", "" }));

        jlFegyver.setText("Van saját fegyvere?");

        btngIgenNem.add(jrbIgen);
        jrbIgen.setText("Igen");

        btngIgenNem.add(jrbNem);
        jrbNem.setText("Nem");

        javax.swing.GroupLayout jpSzemelyes1Layout = new javax.swing.GroupLayout(jpSzemelyes1);
        jpSzemelyes1.setLayout(jpSzemelyes1Layout);
        jpSzemelyes1Layout.setHorizontalGroup(
            jpSzemelyes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSzemelyes1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpSzemelyes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpSzemelyes1Layout.createSequentialGroup()
                        .addComponent(jcbHadsereg, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jpSzemelyes1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jlFegyver)
                        .addGap(46, 46, 46)
                        .addComponent(jrbIgen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrbNem)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jpSzemelyes1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jrbIgen, jrbNem});

        jpSzemelyes1Layout.setVerticalGroup(
            jpSzemelyes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSzemelyes1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jcbHadsereg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpSzemelyes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlFegyver)
                    .addComponent(jrbIgen)
                    .addComponent(jrbNem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Kérem töltse fel a következőket:\n- Személyi Igazolvány\n- Lakcímkártya\n- Adóigazolvány\n- TAJ Kártya\n- Hatástalanítási Igazolás (Ha van)");
        jpFeltoltes.setViewportView(jTextArea1);

        btnFeltoltes.setText("Feltöltés");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpFeltoltes, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnFeltoltes)
                        .addGap(113, 113, 113)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpFeltoltes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFeltoltes)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jpSzemelyes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpSzemelyes1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chbElfogad)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(btnReg)))
                        .addGap(224, 224, 224))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpSzemelyes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpSzemelyes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(81, 81, 81)
                .addComponent(btnReg, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbElfogad)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisztraciosPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisztraciosPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisztraciosPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisztraciosPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisztraciosPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFeltoltes;
    private javax.swing.JButton btnReg;
    private javax.swing.ButtonGroup btngIgenNem;
    private javax.swing.JCheckBox chbElfogad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JComboBox<String> jcbHadsereg;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlFegyver;
    private javax.swing.JLabel jlNev;
    private javax.swing.JLabel jlTelefon;
    private javax.swing.JLabel jlTelefon2;
    private javax.swing.JScrollPane jpFeltoltes;
    private javax.swing.JPanel jpSzemelyes;
    private javax.swing.JPanel jpSzemelyes1;
    private javax.swing.JRadioButton jrbIgen;
    private javax.swing.JRadioButton jrbNem;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfNev;
    private javax.swing.JTextField jtfTelefon;
    private javax.swing.JTextField jtfTelefon2;
    // End of variables declaration//GEN-END:variables
}
